import PDFDocument from "pdfkit";
import type { ResumeDraft } from "@/lib/ai/resume-drafter";

/**
 * Renders the structured ResumeDraft to a PDF buffer using pdfkit.
 *
 * Output: A4 portrait, single column, ATS-friendly:
 *   - System fonts only (Helvetica) — no embedded weird fonts that confuse
 *     OCR-based ATS parsers.
 *   - Bullet-style experience with selectable text.
 *   - Header with name + headline + contact info row.
 *   - Sections: Summary, Experience, Education, Skills, Certifications, Projects.
 *
 * The PDF is intentionally simple visually — fancy CSS would make it look
 * prettier but break a lot of ATS parsers. Trades aesthetic for parsability.
 */
export async function renderResumePdf(draft: ResumeDraft): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 56, left: 56, right: 56, bottom: 56 },
      info: {
        Title: `${draft.header.fullName} — Résumé`,
        Author: draft.header.fullName,
        Subject: "Résumé generated by eMobility Careers",
      },
    });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const TEAL = "#1e2d2a";
    const GREEN = "#5e6764";
    const DARK = "#191919";
    const MUTED = "#8b95a0";

    // ─── Header ──────────────────────────────────────────────
    doc.font("Helvetica-Bold").fontSize(22).fillColor(DARK).text(draft.header.fullName);
    if (draft.header.headline) {
      doc.moveDown(0.15).font("Helvetica").fontSize(11).fillColor(GREEN).text(draft.header.headline);
    }

    const contactBits: string[] = [];
    if (draft.header.location) contactBits.push(draft.header.location);
    if (draft.header.email) contactBits.push(draft.header.email);
    if (draft.header.phone) contactBits.push(draft.header.phone);
    if (draft.header.linkedinUrl) contactBits.push(draft.header.linkedinUrl);
    if (draft.header.githubUrl) contactBits.push(draft.header.githubUrl);
    if (draft.header.portfolioUrl) contactBits.push(draft.header.portfolioUrl);
    if (contactBits.length) {
      doc.moveDown(0.4).font("Helvetica").fontSize(9).fillColor(GREEN).text(contactBits.join("  ·  "));
    }

    drawDivider(doc);

    // ─── Summary ──────────────────────────────────────────────
    if (draft.summary) {
      sectionTitle(doc, "Summary", TEAL);
      doc.font("Helvetica").fontSize(10).fillColor(DARK).text(draft.summary, { align: "justify" });
      doc.moveDown(0.6);
    }

    // ─── Experience ──────────────────────────────────────────
    if (draft.experience.length > 0) {
      sectionTitle(doc, "Experience", TEAL);
      for (const exp of draft.experience) {
        doc.font("Helvetica-Bold").fontSize(11).fillColor(DARK).text(exp.title);
        const sub = [exp.company, exp.location, dateRange(exp.startDate, exp.endDate)].filter(Boolean).join("  ·  ");
        doc.font("Helvetica").fontSize(9).fillColor(GREEN).text(sub);
        if (exp.bullets.length > 0) {
          doc.moveDown(0.15);
          for (const b of exp.bullets) {
            doc.font("Helvetica").fontSize(10).fillColor(DARK).list([b], { bulletRadius: 1.5, textIndent: 12 });
          }
        }
        doc.moveDown(0.4);
      }
    }

    // ─── Education ──────────────────────────────────────────
    if (draft.education.length > 0) {
      sectionTitle(doc, "Education", TEAL);
      for (const ed of draft.education) {
        doc.font("Helvetica-Bold").fontSize(11).fillColor(DARK).text(ed.institution);
        const degreeRow = [ed.degree, ed.field, [ed.startYear, ed.endYear].filter(Boolean).join("–")].filter(Boolean).join("  ·  ");
        if (degreeRow) doc.font("Helvetica").fontSize(9).fillColor(GREEN).text(degreeRow);
        if (ed.grade) doc.font("Helvetica").fontSize(9).fillColor(MUTED).text(ed.grade);
        doc.moveDown(0.3);
      }
    }

    // ─── Skills ──────────────────────────────────────────────
    if (draft.skills.length > 0) {
      sectionTitle(doc, "Skills", TEAL);
      doc.font("Helvetica").fontSize(10).fillColor(DARK).text(draft.skills.join("  ·  "));
      doc.moveDown(0.6);
    }

    // ─── Certifications ──────────────────────────────────────
    if (draft.certifications.length > 0) {
      sectionTitle(doc, "Certifications", TEAL);
      for (const c of draft.certifications) {
        const line = [c.name, c.issuer, c.year].filter(Boolean).join("  ·  ");
        doc.font("Helvetica").fontSize(10).fillColor(DARK).text(line);
      }
      doc.moveDown(0.4);
    }

    // ─── Projects ────────────────────────────────────────────
    if (draft.projects.length > 0) {
      sectionTitle(doc, "Projects", TEAL);
      for (const p of draft.projects) {
        doc.font("Helvetica-Bold").fontSize(11).fillColor(DARK).text(p.title);
        if (p.description) doc.font("Helvetica").fontSize(10).fillColor(DARK).text(p.description);
        const meta = [p.techStack.join(", "), p.url].filter(Boolean).join("  ·  ");
        if (meta) doc.font("Helvetica").fontSize(9).fillColor(GREEN).text(meta);
        doc.moveDown(0.3);
      }
    }

    // ─── Footer ──────────────────────────────────────────────
    drawDivider(doc);
    doc.font("Helvetica-Oblique").fontSize(8).fillColor(MUTED)
      .text(`Generated by eMobility Careers · ${new Date().toLocaleDateString("en-IN", { dateStyle: "medium" })}`, { align: "center" });

    doc.end();
  });
}

function sectionTitle(doc: PDFKit.PDFDocument, title: string, colour: string) {
  doc.moveDown(0.3);
  doc.font("Helvetica-Bold").fontSize(10).fillColor(colour).text(title.toUpperCase(), { characterSpacing: 1 });
  doc.moveDown(0.2);
  const y = doc.y;
  doc.strokeColor("#d4e8d8").lineWidth(0.5)
    .moveTo(doc.page.margins.left, y)
    .lineTo(doc.page.width - doc.page.margins.right, y)
    .stroke();
  doc.moveDown(0.4);
}

function drawDivider(doc: PDFKit.PDFDocument) {
  doc.moveDown(0.5);
  const y = doc.y;
  doc.strokeColor("#d4e8d8").lineWidth(0.5)
    .moveTo(doc.page.margins.left, y)
    .lineTo(doc.page.width - doc.page.margins.right, y)
    .stroke();
  doc.moveDown(0.5);
}

function dateRange(start: string | undefined, end: string | undefined): string {
  if (!start) return "";
  const fmt = (s: string) => s === "Present" ? "Present" : s.length === 7 ? formatYearMonth(s) : s;
  return `${fmt(start)}${end ? ` – ${fmt(end)}` : ""}`;
}

function formatYearMonth(yyyymm: string): string {
  const [y, m] = yyyymm.split("-");
  if (!y || !m) return yyyymm;
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  const idx = Number(m) - 1;
  return `${months[idx] ?? m} ${y}`;
}
