import "server-only";

import { db } from "@/lib/db";

/**
 * Verified Company badge plumbing — shared helpers used by the
 * server-action layer + the profile UI.
 *
 * The badge ("✓ Engineer at Ather") lights up on an Experience row
 * when ANY of three conditions is met:
 *
 *   • EMAIL_DOMAIN — candidate verified an OTP sent to an address
 *                    matching `Company.emailDomains` (e.g. ather.com).
 *   • RECRUITER_APPROVAL — a verified employer at the SAME company
 *                          approved the claim from the recruiter dashboard.
 *   • ADMIN — manual override via /admin (not exposed yet, kept for
 *             trust escalations).
 *
 * The verification state is stamped directly on the Experience row
 * (verifiedAt + verifiedMethod + verifiedEmail/verifiedByUserId for
 * audit). One-shot — re-verification is a no-op.
 */

/** Strip the local-part, lowercase, and trim. `anita.k+ev@ather.com` → `ather.com`. */
export function emailDomain(email: string): string | null {
  const at = email.lastIndexOf("@");
  if (at < 0) return null;
  const dom = email.slice(at + 1).trim().toLowerCase();
  return dom.length > 0 ? dom : null;
}

/**
 * Find the Company whose `emailDomains` list contains the given email's
 * domain. Returns null when no company matches (we never auto-create a
 * company from an email — that path goes through the company onboarding flow).
 */
export async function findCompanyByEmailDomain(email: string): Promise<{ id: string; name: string } | null> {
  const dom = emailDomain(email);
  if (!dom) return null;
  const company = await db.company.findFirst({
    where: { emailDomains: { has: dom } },
    select: { id: true, name: true },
  });
  return company;
}

/**
 * Stamp every Experience row of `candidateId` whose `companyId` is
 * `companyId` AND that doesn't already have a verifiedAt as VERIFIED.
 *
 * Returns the number of rows updated. Used by `confirmExperienceEmailVerify`
 * which fires after a successful OTP-link click — verifying one email
 * verifies all positions at that company in one motion.
 */
export async function stampExperiencesForCompany(opts: {
  candidateId: string;
  companyId: string;
  email: string;
  method: "EMAIL_DOMAIN" | "RECRUITER_APPROVAL" | "ADMIN";
  verifierUserId?: string | null;
}): Promise<number> {
  const result = await db.experience.updateMany({
    where: {
      candidateId: opts.candidateId,
      companyId: opts.companyId,
      verifiedAt: null,
    },
    data: {
      verifiedAt: new Date(),
      verifiedMethod: opts.method,
      verifiedEmail: opts.method === "EMAIL_DOMAIN" ? opts.email.toLowerCase() : null,
      verifiedByUserId: opts.verifierUserId ?? null,
    },
  });
  return result.count;
}

/**
 * Build the URL the candidate clicks from their email. The token half
 * is generated by `issueToken("experience-verify", identifier)` where
 * `identifier` is the experienceId (we don't need the email — once the
 * link is clicked we already know the OTP was delivered to a verified
 * address).
 */
export function experienceVerifyUrl(token: string, baseUrl: string): string {
  return `${baseUrl.replace(/\/$/, "")}/verify-experience?token=${encodeURIComponent(token)}`;
}
