import { S3Client, PutObjectCommand, GetObjectCommand, DeleteObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { env } from "@/lib/env";
import crypto from "node:crypto";

/**
 * The "internal" S3 client. Used by every server-side action that
 * actually puts/gets objects — uploads, downloads streamed through
 * proxy routes, deletions. The endpoint here is the network address
 * the *web container* uses to reach MinIO (typically `minio:9000`
 * inside Docker or `127.0.0.1:9000` on the host). NOT browser-reachable.
 */
export const s3 = new S3Client({
  region: env.S3_REGION,
  endpoint: env.S3_ENDPOINT,
  forcePathStyle: env.S3_FORCE_PATH_STYLE,
  credentials: {
    accessKeyId: env.S3_ACCESS_KEY,
    secretAccessKey: env.S3_SECRET_KEY,
  },
});

/**
 * The "public" S3 client — same credentials, but the endpoint is the
 * browser-reachable URL configured in `S3_PUBLIC_URL`. We use this
 * client ONLY for generating presigned URLs (uploads + downloads).
 *
 * Why two clients: a presigned URL is signed against the endpoint
 * baked into the client. If the internal client (host `minio:9000`)
 * generates a URL, the browser can't fetch it — different host,
 * signature wouldn't match either way. Generating against the public
 * endpoint gives the browser a URL it can hit, and MinIO (behind
 * Caddy / your reverse proxy) accepts the signature because it shares
 * the same credentials.
 *
 * Setup expectation: `S3_PUBLIC_URL` points at your Caddy-proxied
 * MinIO endpoint (e.g. `https://files.emobility.careers` or
 * `https://emobility.careers/files`). Caddy's reverse_proxy directive
 * forwards to the internal `minio:9000`. As long as both clients have
 * the same access key + secret, signatures generated by either client
 * are valid against either endpoint.
 *
 * If S3_PUBLIC_URL isn't a publicly-reachable MinIO endpoint (e.g.
 * during local dev where it equals S3_ENDPOINT), the URLs still work
 * because the dev MinIO is on localhost which the browser can reach.
 */
export const s3Public = new S3Client({
  region: env.S3_REGION,
  endpoint: env.S3_PUBLIC_URL,
  forcePathStyle: env.S3_FORCE_PATH_STYLE,
  credentials: {
    accessKeyId: env.S3_ACCESS_KEY,
    secretAccessKey: env.S3_SECRET_KEY,
  },
});

export const buckets = {
  resumes: env.S3_BUCKET_RESUMES,
  avatars: env.S3_BUCKET_AVATARS,
  logos: env.S3_BUCKET_LOGOS,
  docs: env.S3_BUCKET_DOCS,
  // Public bucket for media that's rendered as <img src=...> in the
  // browser — post attachments, event covers, etc. The `docs` bucket
  // is intentionally PRIVATE (Aadhar uploads, GDPR exports), so post
  // media that piggybacked on it returned AccessDenied for every
  // anonymous read. Use `posts` for any new public media.
  posts: env.S3_BUCKET_POSTS,
} as const;

export type BucketName = keyof typeof buckets;

export function publicUrl(bucket: BucketName, key: string): string {
  return `${env.S3_PUBLIC_URL}/${buckets[bucket]}/${key}`;
}

export async function presignUpload(
  bucket: BucketName,
  key: string,
  contentType: string,
  expiresIn = 60 * 5,
): Promise<{ url: string; key: string }> {
  const cmd = new PutObjectCommand({
    Bucket: buckets[bucket],
    Key: key,
    ContentType: contentType,
  });
  // Sign against the public endpoint so the URL we hand back to the
  // browser actually resolves. See `s3Public` above for the rationale.
  const url = await getSignedUrl(s3Public, cmd, { expiresIn });
  return { url, key };
}

export async function presignDownload(
  bucket: BucketName,
  key: string,
  expiresIn = 60 * 5,
): Promise<string> {
  const cmd = new GetObjectCommand({ Bucket: buckets[bucket], Key: key });
  return getSignedUrl(s3Public, cmd, { expiresIn });
}

export async function deleteObject(bucket: BucketName, key: string): Promise<void> {
  await s3.send(new DeleteObjectCommand({ Bucket: buckets[bucket], Key: key }));
}

export function objectKey(prefix: string, ext: string): string {
  const random = crypto.randomBytes(8).toString("hex");
  const date = new Date().toISOString().slice(0, 10);
  return `${prefix}/${date}/${random}.${ext.replace(/^\./, "")}`;
}
