import { NextRequest } from "next/server";
import { GetObjectCommand } from "@aws-sdk/client-s3";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { audit } from "@/lib/audit";
import { logger } from "@/lib/logger";
import { s3, buckets } from "@/lib/storage";

/**
 * Admin proxy for ID-verification documents (Aadhar, etc.).
 *
 * Why a proxy instead of a presigned URL:
 *
 *   1. The `docs` MinIO bucket is private and lives on an internal
 *      hostname (`minio:9000` inside Docker, `127.0.0.1:9000` on the
 *      host) that the admin's browser can't reach. A presigned URL
 *      generated by the SDK against the internal endpoint signs
 *      against `127.0.0.1:9000/...` — the URL doesn't resolve from
 *      the public internet.
 *
 *   2. Aadhar / government ID images are highly sensitive PII. A
 *      presigned URL — once issued — works for anyone with the link
 *      until expiry. Screenshotting the queue, copying a debug
 *      session, or accidentally sharing the link all leak the doc.
 *      An admin-gated proxy validates the session on every request,
 *      so the only way to view the doc is to be signed in as an admin.
 *
 *   3. We can audit-log every view here. DPDP / GDPR + internal
 *      governance both want a tamper-evident trail of who looked at
 *      whose ID and when.
 *
 * Authorization:
 *   • Admin role required.
 *   • Caller must pass `?profileId=<candidateProfileId>`. We look up
 *     the row, derive the bucket key from the stored `idVerificationDocUrl`,
 *     and stream that exact key. Admins can't pass arbitrary keys —
 *     they can only fetch the doc tied to a real verification request.
 *
 * The response sets `Content-Disposition: inline` so the image opens
 * in the browser tab (PDFs render natively too). 5-minute Cache-Control
 * prevents the file from sticking around in any shared HTTP cache.
 */

function bucketKeyFromStoredUrl(url: string | null): string | null {
  if (!url) return null;
  // The stored URL is `${S3_PUBLIC_URL}/${bucketName}/${key}` — see
  // `publicUrl()` in lib/storage.ts. Recover {key} by splitting on
  // the bucket-name segment. Belt-and-braces: also accept the raw
  // key form in case future code stores it that way.
  const bucketMarker = `/${buckets.docs}/`;
  const idx = url.indexOf(bucketMarker);
  if (idx >= 0) return url.slice(idx + bucketMarker.length);
  // No bucket marker — assume the value already IS the key. Defensive
  // for future changes.
  return url;
}

export async function GET(req: NextRequest) {
  const session = await auth();
  if (session?.user?.role !== "ADMIN") {
    return new Response("Forbidden", { status: 403 });
  }
  const url = new URL(req.url);
  const profileId = url.searchParams.get("profileId");
  if (!profileId) {
    return new Response("Missing profileId", { status: 400 });
  }

  const profile = await db.candidateProfile.findUnique({
    where: { id: profileId },
    select: {
      id: true,
      idVerificationDocUrl: true,
      idVerificationStatus: true,
      firstName: true,
      lastName: true,
    },
  });
  if (!profile) {
    return new Response("Profile not found", { status: 404 });
  }
  // We only proxy docs that are PENDING / VERIFIED / REJECTED (i.e.,
  // a doc has been submitted at some point). NONE → no doc to fetch.
  if (!profile.idVerificationDocUrl) {
    return new Response("No document on file", { status: 404 });
  }

  const key = bucketKeyFromStoredUrl(profile.idVerificationDocUrl);
  if (!key) {
    return new Response("Could not resolve document key", { status: 500 });
  }

  // Audit-log the view BEFORE the actual fetch so a tampering admin
  // can't fetch + roll back logging. Best-effort — a failed audit
  // shouldn't block the fetch, since denying review of legitimate
  // requests would create its own privacy / fairness problems.
  void audit({
    actorId: session.user.id,
    action: "id_verification.doc_viewed",
    entity: "CandidateProfile",
    entityId: profile.id,
    meta: { status: profile.idVerificationStatus },
  });

  let body: ReadableStream<Uint8Array> | null = null;
  let contentType = "application/octet-stream";
  let contentLength: number | null = null;
  try {
    const obj = await s3.send(
      new GetObjectCommand({
        Bucket: buckets.docs,
        Key: key,
      }),
    );
    if (!obj.Body) {
      return new Response("Empty body from storage", { status: 502 });
    }
    // The SDK returns a node Readable; in route handlers we need a
    // Web ReadableStream. transformToWebStream() bridges them
    // without buffering the whole file in memory — important for
    // larger PDF scans.
    body = (obj.Body as { transformToWebStream(): ReadableStream<Uint8Array> })
      .transformToWebStream();
    contentType = obj.ContentType ?? "application/octet-stream";
    contentLength = typeof obj.ContentLength === "number" ? obj.ContentLength : null;
  } catch (err) {
    logger.error(
      { err, profileId, key, bucket: buckets.docs },
      "[id-doc-proxy] fetch failed",
    );
    return new Response(
      "Couldn't fetch the document — check that the bucket exists and is reachable from the web container.",
      { status: 502 },
    );
  }

  // Friendly filename for the download. Keeps PII out of the URL —
  // we only embed first name. For PDF/image, browsers render inline.
  const ext = guessExtension(contentType);
  const filename = `id-${profile.firstName.toLowerCase().replace(/[^a-z0-9]/g, "")}-${profile.id.slice(-6)}${ext}`;

  return new Response(body, {
    status: 200,
    headers: {
      "Content-Type": contentType,
      "Content-Disposition": `inline; filename="${filename}"`,
      "Cache-Control": "private, no-store",
      ...(contentLength !== null
        ? { "Content-Length": String(contentLength) }
        : {}),
      // Defence-in-depth: even though Content-Disposition is `inline`,
      // we don't want a PDF / SVG to execute scripts.
      "X-Content-Type-Options": "nosniff",
      "Content-Security-Policy": "default-src 'none'; img-src 'self'",
    },
  });
}

function guessExtension(ct: string): string {
  if (ct.startsWith("image/jpeg")) return ".jpg";
  if (ct.startsWith("image/png")) return ".png";
  if (ct.startsWith("image/webp")) return ".webp";
  if (ct.startsWith("application/pdf")) return ".pdf";
  return "";
}
