import Link from "next/link";
import { redirect } from "next/navigation";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { AdminShell } from "@/components/layout/admin-shell";
import { WordPressImportForm } from "@/components/admin/WordPressImportForm";
import { relativeTime } from "@/lib/utils";

export const metadata = { title: "WordPress content import" };

/**
 * Importer for WordPress pages + posts. Sibling to /admin/import
 * which handles user/company/job migration via the legacy
 * `wpLegacyId` columns. This route is content-only — pages land
 * in the new `Page` table, posts land in `Article`.
 */
export default async function WordPressContentImportPage() {
  const session = await auth();
  if (session?.user?.role !== "ADMIN") redirect("/403");

  // Last 20 batches with at-a-glance stats. The full audit log is
  // in /admin/audit if anyone needs the full meta blob.
  const batches = await db.wordPressImportBatch.findMany({
    orderBy: { createdAt: "desc" },
    take: 20,
    include: {
      uploadedBy: { select: { name: true, email: true } },
      _count: { select: { pages: true } },
    },
  });

  return (
    <AdminShell>
      <div className="space-y-6 px-4 py-6 lg:px-8 lg:py-8">
        <header>
          <h1 className="text-dashboard text-emce-text md:text-3xl">
            WordPress content import
          </h1>
          <p className="mt-1 text-sm text-emce-text-sec">
            Pull pages and posts out of a WordPress XML export and stage them as
            drafts. Different surface from{" "}
            <Link href="/admin/import" className="font-bold text-emce-dark hover:underline">
              user / company / job import
            </Link>{" "}
            — that one handles the audience migration; this one handles the editorial archive.
          </p>
        </header>

        <Card className="p-6">
          <h2 className="text-section text-emce-text">Upload an XML export</h2>
          <p className="mt-1 text-sm text-emce-text-sec">
            Generated by WordPress at <em>Tools &rarr; Export</em>. Pages and posts
            in the same file are routed to the right table automatically.
          </p>
          <div className="mt-4">
            <WordPressImportForm />
          </div>
        </Card>

        <Card className="p-6">
          <div className="flex items-baseline justify-between">
            <h2 className="text-section text-emce-text">Recent imports</h2>
            <span className="text-hint text-emce-text-sec">{batches.length} most recent</span>
          </div>
          {batches.length === 0 ? (
            <div className="mt-4 rounded-md border border-dashed border-emce-border p-8 text-center">
              <p className="text-sm text-emce-text">No imports yet</p>
              <p className="mt-1 text-hint text-emce-text-sec">
                Once you upload above, every batch shows up here with row counts.
              </p>
            </div>
          ) : (
            <ul className="mt-3 divide-y divide-emce-border">
              {batches.map((b) => (
                <li key={b.id} className="py-3">
                  <div className="flex flex-wrap items-baseline justify-between gap-2">
                    <div>
                      <p className="text-sm font-bold text-emce-text">{b.fileName}</p>
                      <p className="text-hint text-emce-text-sec">
                        {b.uploadedBy?.name ?? b.uploadedBy?.email ?? "Unknown"} &middot;{" "}
                        {relativeTime(b.createdAt)}
                      </p>
                    </div>
                    <div className="flex items-center gap-2">
                      <Badge variant="outline" size="sm">
                        {b.itemsImported} / {b.itemsTotal} imported
                      </Badge>
                      {b._count.pages > 0 && (
                        <Badge variant="default" size="sm">
                          {b._count.pages} pages
                        </Badge>
                      )}
                    </div>
                  </div>
                  {b.notes && (
                    <p className="mt-1 text-hint text-emce-text-muted">{b.notes}</p>
                  )}
                </li>
              ))}
            </ul>
          )}
        </Card>

        <p className="text-center text-hint text-emce-text-sec">
          Every imported item lands as DRAFT. Publish individually from{" "}
          <Link href="/admin/pages" className="font-bold text-emce-dark hover:underline">
            /admin/pages
          </Link>{" "}
          or{" "}
          <Link href="/admin/articles" className="font-bold text-emce-dark hover:underline">
            /admin/articles
          </Link>
          .
        </p>
      </div>
    </AdminShell>
  );
}
